'use client';

import Link from 'next/link';
import { ArrowRight, BookOpen, Clock3 } from 'lucide-react';
import type { Course, Enrollment, AssignmentSubmission, Assignment } from '@/lib/types';

export function StudentCourseList({ courses, enrollments, assignments, submissions }: { courses: Course[]; enrollments: Enrollment[]; assignments: Assignment[]; submissions: AssignmentSubmission[] }) {
    if (enrollments.length === 0) {
        return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><BookOpen className="mx-auto h-8 w-8 text-slate-400" /><h2 className="mt-4 text-lg font-semibold text-slate-950">Start your learning journey</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">You aren&apos;t enrolled in a course yet. Explore available courses and find something to learn.</p><Link href="/courses" className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#18375f] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#102a4a]">Explore Courses<ArrowRight className="h-4 w-4" /></Link></div>;
    }
    return <div className="grid gap-4 lg:grid-cols-2">{enrollments.map((enrollment) => { const course = courses.find((item) => item.id === enrollment.courseId); if (!course) return null; const courseAssignments: Assignment[] = assignments.filter((item) => item.courseId === course.id); const submitted = submissions.filter((item) => courseAssignments.some((assignment) => assignment.id === item.assignmentId)).length; const progress = courseAssignments.length ? Math.round((submitted / courseAssignments.length) * 100) : enrollment.status === 'completed' ? 100 : 0; return <article key={enrollment.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">{course.category}</p><h3 className="mt-1 text-lg font-bold text-slate-950">{course.title}</h3><p className="mt-1 text-sm text-slate-500">Instructor: {course.instructorName}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold capitalize text-slate-600">{course.status || 'upcoming'}</span></div><div className="mt-6"><div className="flex items-center justify-between text-xs"><span className="font-semibold text-slate-700">Progress</span><span className="font-bold text-emerald-700">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600 transition-all" style={{ width: `${progress}%` }} /></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><span className="flex items-center gap-1.5 text-xs text-slate-500"><Clock3 className="h-3.5 w-3.5" />{course.startDate ? `Starts ${new Date(`${course.startDate}T00:00:00`).toLocaleDateString()}` : 'Start date TBD'}</span><Link href={`/courses/${course.id}`} className="inline-flex items-center gap-1.5 rounded-lg bg-[#18375f] px-3 py-2 text-xs font-semibold text-white hover:bg-[#102a4a]">Continue learning<ArrowRight className="h-3.5 w-3.5" /></Link></div></article>; })}</div>;
}
